- name: install postfix and service start
  hosts: localhost
  become: yes
  tasks: 
    - name: Installation
      ansible.builtin.yum:
        name: postfix 
        state: present 
    
    - name: Service Start
      ansible.builtin.service:
        name: postfix
        state: started