- name: variables
  hosts: localhost
  become: yes
  vars: 
    USER: "Srinivasa"
    WISH: "Morning"
    WISH_1: "Morning"
    
  tasks:
    - name: Wishing
      ansible.builtin.debug:
        msg: "Hello {{USER}}, Good {{WISH}}"
        msg: "Hello {{USER}}, Good {{WISH_1}}"
