- name: variables
  hosts: 172.31.29.200
  become: yes
  vars: 
    USER: "Srinivasa"
    WISH: "Morning"
    
  tasks:
    - name: Wishing
      ansible.builtin.debug:
        msg: "Hello {{USER}}, Good {{WISH}}"
