- name: variables
  hosts: localhost
  become: yes
  vars: 
    USER: "Srinivasa"
    WISH: "Morning"
    GOOD NEWS: "selected for Devops Training"
    Fees: "15000"
  tasks:
    - name: Wishing
      ansible.builtin.debug:
        msg: "Hello {{USER}}, Good {{WISH}}"

    - name: Wishing
      ansible.builtin.debug:
        msg: "Congrats!! you are {{GOOD NEWS}} and the fees is {{FEES}}"
