- name: variables
  hosts: localhost
  become: yes
  vars: 
    USER: "Srinivasa"
    WISH: "Morning"    
  tasks:
    - name: Wishing
      vars: 
        WISH: "Afternoon"
      ansible.builtin.debug:
        msg: "Hello {{USER}}, Good {{WISH}}"