- name: PLAY-1 Variables from Files
  hosts: localhost
  become: yes
  vars_files: 
  - variable-file.yaml
  - variable-file-2.yaml
  vars: 
    COMPANY: "HCL"
  tasks: 
  - name: PLAY-1 TASK-1 Variables from Files
    vars: 
      COMPANY: "INFOSYS"
    ansible.builtin.debug:
      msg: "I'm {{CLIENT}} and {{WISH}} {{TRAINER}}. I work at {{COMPANY}}"