- name: Validate and Create the username roboshop
  hosts: localhost
  become: yes
  tasks:

  - name: check if username existed
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - name: print the output saved in user
    ansible.builtin.debug:
      msg: "output is: {{user}}"

  - name: print the rc output
    ansible.builtin.user:
      msg: "rc output is: {{user.rc}}"

  
  


      