- name: Package Installation
  hosts: localhost
  become: yes
  tasks:
    - name: package automatic installation
      ansible.builtin.package:
        name: "{{item.what}}"
        state: "{{item.to}}"
      loop:
        - {what: 'git', to: 'absent'}
        - {what: 'mysql', to: 'absent'}
        - {what: 'postfix', to: 'absent'}
