- name: Package Installation
  hosts: localhost
  become: yes
  tasks:
    - name: package automatic installation
      ansible.builtin.package:
        name: "{{item.name}}"
        state: "{{item.state}}"
        enabled: yes
      loop:
        - {name: 'git', state: 'present'}
        - {name: 'mysql', state: 'present'}
        - {name: 'postfix', state: 'present'}
