- name: Package Installation
  hosts: localhost
  become: yes
  tasks:
    - name: package automatic installation
      ansible.builtin.package:
        name: "{{item.what}}"
        state: "{{item.to}}"
      loop:
        - {what: 'git', to: 'present'}
        - {what: 'mysql', to: 'present'}
        - {what: 'postfix', to: 'present'}

    - name: Service Start
      ansible.builtin.service:
        name: "{{item.what}}"
        enabled: yes
      loop:
        - {what: 'git'}
        - {what: 'mysql'}
        - {what: 'postfix'}
