- name: install nginx and service start
  hosts: all
  become: yes
  tasks: 
    - name: Installation
      ansible.builtin.yum:
        name: ansible 
        state: present 
    
    - name: Service Start
      ansible.builtin.service:
        name: ansible
        state: started