- name: start nginx on ungrouped hosts
  hosts: ungrouped
  become: yes
  tasks: 
    - name: nginx installation
      ansible.builtin.yum:
        name: httpd 
        state: present 

      ansible.builtin.service:
        name: httpd
        state: started
