- name: start nginx on ungrouped hosts
  hosts: ungrouped
  become: yes
  tasks: 
    - name: httpd installation
      ansible.builtin.yum:
        name: httpd 
        state: present 

    - name: httpd service start
      ansible.builtin.service:
        name: httpd
        state: started
